try{
    console.log('No error');
}
catch (error){
    console.log(error);
}
finally{
    console.log('I will run away');
}